# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: purplesquad knowledge base
site_url: https://knowledebase.purplesquad.io/
site_author: purplesquad
site_description: >-
  Add a site description

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
#  custom_dir: material
  language: en
  logo: assets/img/logo.png
  favicon: assets/img/favicon.ico
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/purplesquad-io
    - icon: fontawesome/brands/github
      link: https://github.com/purplesquad-io
  generator: true

repo_url: https://github.com/purplesquad-io/knowledebase
repo_name: knowledebase

copyright: Copyright &copy; 2022 - 2022 purplesquad

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      type: date