# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: purplesquad.io
site_url: https://purplesquad.io/
site_author: purplesquad
site_description: >-
  purplesquad.io - The ethical hacking squad

nav:
#   - Home: index.md
  - Ethical Hacking:
      - Fundamentals:
        - Glossary: ethical-hacking/fundamentals/glossary.md
      - Tools:
        - nmap: ethical-hacking/tools/nmap.md
        - nikto: ethical-hacking/tools/nikto.md
  - Tools and Resources: resources/tools-and-resources.md

theme:
  name: material
  language: en
  logo: assets/img/logo.png
  favicon: assets/img/favicon.ico
  palette:
    scheme: purplesquad
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections

extra_css:
  - stylesheets/extra.css
  -
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/purplesquad-io
    - icon: fontawesome/brands/github
      link: https://github.com/purplesquad-io
  generator: true

repo_url: https://github.com/purplesquad-io/knowledgebase
repo_name: knowledgebase

copyright: Copyright &copy; 2022 - 2023 purplesquad

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      type: date