# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: purplesquad knowledge base
site_url: https://knowledgebase.purplesquad.io/
site_author: purplesquad
site_description: >-
  Add a site description

nav:
  - Home: "index.md"
  - Red team:
    - Overview: "red-team/red-team.md"
  - Blue team:
      - Overview: "blue-team/blue-team.md"
  - Attacks:
      - Overview: "attacks/overview.md"
      - Web Application attacks:
          - SQL injection: "attacks/web-application-attacks/sql-injection.md"
          - Authentication vulnerabilities: "attacks/overview"
          - Directory traversal: "attacks/overview"
          - OS command injection: "attacks/overview"
          - Business logic vulnerabilities: "attacks/overview"
          - Information disclosure vulnerabilities: "attacks/overview"
          - Access control vulnerabilities and privilege escalation: "attacks/overview"
          - File upload vulnerabilities: "attacks/overview"
          - Server-side request forgery (SSRF): "attacks/overview"
          - XML external entity (XXE) injection: "attacks/overview"
          - Cross-site scripting: "attacks/web-application-attacks/cross-site-scripting.md"
      - Network attacks:
          - Man in the middle: "attacks/overview"
          - TCP/IP attacks: "attacks/overview"
          - ARP spoofing: "attacks/overview"
          - DNS spoofing: "attacks/overview"
          - Wireless attacks: "attacks/overview"
  - Resources:
    - Overview: "resources/overview.md"
    - Certification: "resources/certification.md"
    - Tools: "resources/tools.md"
    - Links: "resources/links.md"
  - About: about.md

theme:
  name: material
#  custom_dir: material
  language: en
  logo: assets/img/logo.png
  favicon: assets/img/favicon.ico
  palette:
    scheme: slate
    primary: indigo
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/purplesquad-io
    - icon: fontawesome/brands/github
      link: https://github.com/purplesquad-io
  generator: true

repo_url: https://github.com/purplesquad-io/knowledgebase
repo_name: knowledgebase

copyright: Copyright &copy; 2022 - 2022 purplesquad

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      type: date